---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
apiVersion: v2
name: dm-manager
description: Edge Infrastructure Device Management Resource Manager
type: application
version: 0.7.2
appVersion: "0.7.5"
home: edge-orchestrator.intel.com
annotations: {}
maintainers:
  - name: Edge Infrastructure Manager Team
