# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
{{- with .Values.tenancyMiddleware }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: mps-middleware-configmap
data:
  multiTenancyMiddleware.js: |-
    {{ .Files.Get "multiTenancyMiddleware.js" }}
{{- end }}
