# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---

apiVersion: v2
name: mps
description: Edge Infrastructure Manager AMT MPS
type: application
version: 0.0.8
appVersion: "0.0.8"
annotations: {}
home: edge-orchestrator.intel.com
maintainers:
  - name: Edge Infrastructure Manager Team
