# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.server.ingress.enabled }}
apiVersion: {{ .Values.server.ingress.apiGroup }}
kind: IngressRoute
metadata:
  name: tinkerbell-server-ingress
  namespace: {{ .Values.server.ingress.gatewayNamespace }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.server.ingress.hostname }}`)
      kind: Rule
      middlewares:
        - name: validate-jwt
      services:
        - name: {{ .Values.server.name }}
          port: {{ .Values.server.service.port }}
          scheme: h2c
          namespace: {{ .Release.Namespace | quote }}
  tls:
    secretName: {{ .Values.server.ingress.secretName }}
{{- end }}
