# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---

apiVersion: v2
name: rps
description: Edge Infrastructure Manager AMT RPS
type: application
version: 0.0.21
appVersion: "0.0.13"
annotations: {}
home: edge-orchestrator.intel.com
maintainers:
  - name: Edge Infrastructure Manager Team
